### ISSUE TITLE
Add option to download Spark from a custom URL

### ISSUE THREAD

**Issue by rmessner** [nchammas/flintrock#101]
We are trying to setup a cluster with Spark 1.6.1, without HDFS, but it fails.
The reason is that the file downloaded is corrupted, so we can't untar it.

Would be a nice feature to allow user to specify an alternate mirror to download the pre-build spark. This would add a new key to configuration, like : 

```
services:
  spark:
    version: 1.6.0
    preferred-mirror: http://apache.crihan.fr/dist/spark/spark-${spark_version}/${file}
```

The default value would be `https://s3.amazonaws.com/spark-related-packages/${file}` and the variables available `file` ( as the file name of pre-build spark is always the same whatever the mirror is ), `spark_version` ( e.g. : 1.6.1) , `distribution` ( e.g. : hadoop2.6 )

Related to #71.
