### ISSUE TITLE
Add support for Ganglia

### ISSUE THREAD

**Issue by dm-tran** [nchammas/flintrock#106]
Thanks for creating flintrock and making it open source, it's really fast.

My team and I are moving from spark-ec2 to flintrock. One thing that is missing is the support for ganglia, to monitor Spark clusters.

A user should be able to specify the version and (de)activate ganglia's installation, e.g. : 
```
services:
  spark:
    version: 1.6.0
  hdfs:
    version: 2.7.1
  ganglia:
    version: x.y.z

[...]

launch:
  num-slaves: 1
  # install-hdfs: True
  # install-spark: False
  install-ganglia: True
```
