### ISSUE TITLE
new AMI fails to launch the spark cluster

### ISSUE THREAD

**Issue by xiandong79** [nchammas/flintrock#227]
I would like to run [BigDL](https://bigdl-project.github.io/master/#ProgrammingGuide/run-on-ec2/) on spark cluster https://bigdl-project.github.io/master/#ProgrammingGuide/run-on-ec2/. The AMI is 

![wx20171201-122522](https://user-images.githubusercontent.com/22584737/33467853-c318bb2a-d692-11e7-9ff3-a30962d13e46.png)

ERROR info is:
```
Do you want to terminate the 5 instances created by this operation? [Y/n]: n
[107.23.150.80] bash: line 2: python: command not found
```

My config is 
```
provider: ec2

services:
  spark:
    version: 2.2.0

  hdfs:
    version: 2.7.3

launch:
  num-slaves: 4

providers:
  ec2:
    key-name: Virginia-us-east-1
    identity-file: /Users/dong/Virginia-us-east-1.pem
    instance-type: m4.large
    region: us-east-1
    ami: ami-8c87099a
    user: ubuntu
```
