### ISSUE TITLE
Launching Cluster with specific IAM identity

### ISSUE THREAD

**Issue by DataWookie** [nchammas/flintrock#269]
Hi,

I'm having trouble following the instructions in the README for accessing S3. Actually battling to get past the first step (launching cluster with specific IAM role).

I have the following two IAM users:

`administrator` (AdministratorAccess policy)
`datawookie` (AmazonEC2FullAccess and AmazonS3FullAccess policies)

I want to launch my cluster using the later identity. This is the relevant portion of my `config.yaml`:

```
providers:
   ec2:
     key-name: ethane
     identity-file: /home/colliera/.ssh/id_rsa
     instance-type: t2.small
     instance-profile-name: datawookie
     region: us-east-2
     ami: ami-40142d25
     user: ec2-user
 ```

When I attempt to launch a cluster I get the following error:

```
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetInstanceProfile operation: User: arn:aws:iam::690534650866:user/datawookie is not authorized to perform: iam:GetInstanceProfile on resource: instance profile administrator
```

Note that this seems to mention both the `datawookie` and `administrator` profiles.

I then added the `GetInstanceProfile` permissions to the `datawookie` as an inline policy. Now launching the cluster gives this error:

```
botocore.errorfactory.NoSuchEntityException: An error occurred (NoSuchEntity) when calling the GetInstanceProfile operation: Instance Profile datawookie cannot be found.
```
I'm sure that there is a simple explanation for this. Do you have any ideas?

I'm running flintrock 0.10.0 on Ubuntu 18.04.

Thanks,
Andrew.
