### ISSUE TITLE
Spark 3.0.0 incompatibilities

### ISSUE THREAD

**Issue by Wadaboa** [nchammas/flintrock#313]
Hi,
I'm using Flintrock to deploy a Scala/Spark application to a simple EC2 cluster (master + 1 slave), but I'm having some problems. In particular, I'm using the following custom Flintrock configuration to launch the cluster:
```yaml
provider: ec2

services:
  spark:
    version: 3.0.0

launch:
  num-slaves: 1
  install-spark: True

providers:
  ec2:
    key-name: my-key-pair
    identity-file: my-key-pair.pem
    instance-type: m4.large
    region: us-east-1
    ami: ami-00b882ac5193044e4
    user: ec2-user
    instance-profile-name: ec2-s3

debug: true
```

As you can see, I'm using Spark 3.0.0. Once I have packaged my Scala application (using `sbt`) I perform a Flintrock's `copy-file` operation. Then, when I want to run the JAR using `spark-submit`, I have issues:
* If I run `spark-submit` from my local machine using option `--master spark://<ec2-master-name>:7077` and `--deploy-mode cluster`, I get a Java error saying `Cannot run program "/usr/local/opt/openjdk@11/bin/java" (in directory "/home/ec2-user/spark/work/driver-20200718133018-0005")`
* If I run `spark-submit` from inside the master cluster (using either Flintrock's `run-command --master-only` or `login` commands), the job gets correctly submitted, but the spark UI is not reporting it (at `<ec2-master-name>:8080`). Instead, the application execution can be viewed at `<ec2-master-name>:4040`, even though in the `Executors` page only the master seems to be active.

I can't wrap my head around this problem. I don't know if it is some kind of Flintrock's compatibility issue with Spark 3.0.0, or I'm doing something wrong.
I apologize if this is the wrong place where to post this kind of doubts.

However, my environment is the following:
* Flintrock version: `1.0.0`
* Python version: `3.8.4`
* OS: `macOS Catalina 10.15.5`
* SBT version: `1.3.13`
* Scala version: `2.12.10`
* OpenJDK version: `1.8`

**Comment by nchammas** [comment]
Thanks for sharing this report, @Wadaboa. This is the correct place to report issues like this.

I haven't tested Flintrock myself with Spark 3.0 yet, so I'm not surprised there are issues.

> Cannot run program "/usr/local/opt/openjdk@11/bin/java" (in directory "/home/ec2-user/spark/work/driver-20200718133018-0005")

This looks interesting. Flintrock currently only ensures that Java 8 is available, not Java 11. Spark 3.0 should still work with Java 8, though. Something is causing Spark to look at Java 11.

Are you sure you've built your application against Java 8?

Another possibility is that there is some setting we need to provide to tell Spark 3.0 to use Java 8. The [migration guide](https://spark.apache.org/docs/3.0.0/migration-guide.html) doesn't mention anything like that, but I haven't looked closely. Maybe try setting `JAVA_HOME` to point specifically at the Java 8 home directory.

**Comment by Wadaboa** [comment]
I'm sure I've built my Scala application using Java 8, since running `sbt package` gives me the following output on the very first line:
```bash
[info] welcome to sbt 1.3.13 (AdoptOpenJDK Java 1.8.0_252)
```

(I'm using [jenv](https://github.com/jenv/jenv) to manage different Java versions).

Moreover, building the application on my local machine with Java 8 or Java 11 makes no difference: `spark-submit` works properly locally.

I also tried to build the application using Java 11, installing Java 11 (I tried with both `sudo amazon-linux-extras install java-openjdk11` and [Amazon Corretto 11](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/what-is-corretto-11.html)) on the master node and setting Java 11 as the standard Java version (by using `alternatives --config java`), but It didn't work out.

I assume that to make this "hack" work I would also have to install Java 11 on each slave node, but I was expecting at least some kind of different output/error when launching `spark-submit` on the cluster, which wasn't the case.

One thing I noticed while looking for [Spark's brew formula](https://formulae.brew.sh/formula/apache-spark) is that it requires `openjdk@11`, even though Spark documentation clearly states that version 3.0.0 is still compatible with Java 1.8.

**Comment by nchammas** [comment]
I would try on each cluster node to set `JAVA_HOME` in spark-env.sh to the Java 8 home and see if that solves the problem.

**Comment by Wadaboa** [comment]
I tried setting `JAVA_HOME` in spark-env.sh on each cluster node, by adding the following line:
```bash
export JAVA_HOME="/usr/lib/jvm/jre"
```

The `openjdk@11` error is still there. I tried to execute `spark-submit` both from my local machine and from within the master node, but I get the same behavior as I originally reported.

**Comment by nchammas** [comment]
This is strange. I will give things a shot myself later this week and see if I can get to the bottom of what's going on.

**Comment by Wadaboa** [comment]
I managed to make it work by doing something sketchy. First of all, I changed my custom Flintrock configuration to be:
```yaml
provider: ec2

services:
  spark:
    version: 3.0.0
  hdfs:
    version: 2.8.5

launch:
  num-slaves: 1
  install-spark: True
  install-hdfs: True

providers:
  ec2:
    key-name: my-key-pair
    identity-file: my-key-pair.pem
    instance-type: t2.xlarge
    region: us-east-1
    ami: ami-0f84e2a3635d2fac9
    user: ec2-user
    instance-profile-name: ec2-s3

debug: true
```

Then, after launching the cluster, I ran the following commands:
```bash
flintrock run-command <cluster-name> "sudo amazon-linux-extras install -y java-openjdk11"
flintrock run-command <cluster-name> "yes 2 | sudo alternatives --config java"
flintrock run-command <cluster-name> "sudo mkdir -p /usr/local/opt/openjdk@11/bin/"
flintrock run-command <cluster-name> "sudo ln -s /usr/lib/jvm/jre/bin/java /usr/local/opt/openjdk@11/bin/"
```

Obviously, this is not the go-to solution, but at least it's something. My biggest doubt is still about the `/usr/local/opt/openjdk@11/bin/java` error, which I think could be related to my local machine, but I really don't know how.
