### ISSUE TITLE
Add option to download Hadoop from a custom URL

### ISSUE THREAD

**Issue by nchammas** [nchammas/flintrock#71]
As a follow-up to the discussion in #66, perhaps we should add an option to let users download Hadoop from a custom URL.

* Command-line option: `--hdfs-download-source`
* Config file option:

  ```yaml
modules:
  hdfs:
    version: 2.7.1
    download-source: "http://www.apache.org/dyn/closer.lua/hadoop/common/hadoop-{v}/hadoop-{v}.tar.gz?as_json"
```

`{v}` will be replaced by the HDFS version passed in to Flintrock, either via the config file or via the command line.

The `.../dyn/closer.lua/...` value will be Flintrock's internal default, which the user can replace with a specific Apache mirror, or some other source. The only requirements are that the package be downloadable from the cluster without authentication, and that the URL contain the `{v}` template somewhere.

I would like to deprecate this option as soon as we have a more robust way of downloading Hadoop quickly and reliably, since that's the main motivation for adding this option in.

Related to #66, #69, #84.
